
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
urlpatterns = [
     path('', views.index,name='index'),
     path('index', views.index,name='index'),
     path('like', views.like,name='like'),
     path('home', views.contact_email,name='home'),
     path('privatespace_login', views.privatespace_login,name='privatespace_login'),
     path('login', views.login,name='login'),
     path('privatespace', views.privatespace,name='privatespace'),
     path('forgotpass', views.forgotpass,name='forgotpass'),
     path('otp', views.otp,name='otp'),
     path('changepass', views.changepass,name='changepass'),
     path('password_find', views.password_find,name='password_find'),
     path('findpass', views.findpass,name='findpass'),
     path('addfile', views.addfile,name='findpass'),
     path('editfile', views.editfile,name='editfile'),
     path('deletefile', views.deletefile,name='deletefile'),
     path('addeducation', views.addeducation,name='addeducation'),
     path('editeducation', views.editeducation,name='editeducation'),
     path('editeducationdata', views.editeducationdata,name='editeducationdata'),
     path('deleducationdata', views.deleducationdata,name='deleducationdata'),
     path('addjob', views.addjob,name='addjob'),
     path('editjobpage', views.editjobpage,name='editjobpage'),
     path('deljobdata', views.deljobdata,name='deljobdata'),
     path('editjobdata', views.editjobdata,name='editjobdata'),
     path('addskill', views.addskill,name='addskill'),
     path('editskillpage', views.editskillpage,name='editskillpage'),
     path('delskilldata', views.delskilldata,name='delskilldata'),
     path('editskilldata', views.editskilldata,name='editskilldata'),
     path('addaccomp', views.addaccomp,name='addaccomp'),
     path('editaccomppage', views.editaccomppage,name='editaccomppage'),
     path('delaccompdata', views.delaccompdata,name='delaccompdata'),
     path('editaccompdata', views.editaccompdata,name='editaccompdata'),
     path('delete_all_files', views.delete_all_files,name='delete_all_files'),
     path('websitepage', views.websitepage,name='websitepage'),
     path('addstatic', views.addstatic,name='addstatic'),
     path('editstatic', views.editstatic,name='editstatic'),
     path('delstatic', views.delstatic,name='delstatic'),
     path('addanim', views.addanim,name='addanim'),
     path('editanim', views.editanim,name='editanim'),
     path('delanim', views.delanim,name='delanim'),
     path('adddyno', views.adddyno,name='adddyno'),
     path('editdyno', views.editdyno,name='editdyno'),
     path('deldyno', views.deldyno,name='deldyno'),
     path('showanim', views.showanim,name='showanim'),
     path('showdyno', views.showdyno,name='showdyno'),
     path('showstatic', views.showstatic,name='showstatic'),
     path('likeanim', views.likeanim,name='likeanim'),
     path('likestatic', views.likestatic,name='likestatic'),
     path('likedyno', views.likedyno,name='likedyno'),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)