# Generated by Django 3.2.6 on 2021-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_app', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='per_got',
        ),
        migrations.RemoveField(
            model_name='job',
            name='per_total',
        ),
        migrations.AddField(
            model_name='job',
            name='place',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
