# Generated by Django 3.2.6 on 2021-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_app', '0003_auto_20210824_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=30)),
            ],
        ),
    ]
