# Generated by Django 3.2.6 on 2021-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_app', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('img', models.ImageField(null=0, upload_to='pics/accomplishments/')),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
