# Generated by Django 3.2.6 on 2021-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_app', '0008_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
