# Generated by Django 3.2.6 on 2021-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website_app', '0009_files_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.FileField(null=0, upload_to='files/'),
        ),
    ]
